### ISSUE TITLE
Löytämiäni vikoja Karan sivuilta

### ISSUE THREAD

**Issue by Joquliina** [Ixynas/karanteeni.github.io#7]
- https://karanteeni.net/maailmat sivun Creative-alaotsikon alla oleva "sääntöjen" linkki vie survivalin sääntöihin.
- https://karanteeni.net/maailmat sivulta puuttuu tieto siitä, että jotkin maailmat eivät toimi.
- https://karanteeni.net/yleistietoa sivulla väitetään että palvelimella olisi SkyBlock.
- https://karanteeni.net/yleistietoa sivun linkit voisivat avautua automaattisesti uuteen välilehteen.
- https://karanteeni.net/yllapito HTML-koodin rivillä 107 on ylimääräinen </p>.
- https://karanteeni.net/ukk sivulla "Apua Taloani on grieffattu!" ehdottaa käyttämään rikkinäistä /discord-komentoa.
- https://karanteeni.net/ukk sivulla kerrotaan arkkukaupasta, joka ei toimi. Samassa kohtaa lukee myös "Shiftpainettuna" yhteen.
- https://karanteeni.net/ukk sivulla "Mitä valuuttaa palvelin käyttää ja kuinka saan sitä?" kertoo rikkinäisestä äänestyksestä ja rikkinäisestä arkkukaupasta.
- https://karanteeni.net/ukk sivulla kaikki erikseen kirjoitettavat sanat missä on laitettu "\r" näkyvät selaimessa yhteen kirjoitettuna: esim. "liittyäuudelleen" kohdassa "Apua! Ei ole oikeuksia komentoon, vaikka pitäisi olla".
- https://karanteeni.net/chat-saannot sivulla olevasta säännöstä "Pidetään chatti siistinä..." puuttuu piste lopusta.
- https://karanteeni.net/saannot vain osassa säännöissä on piste perässä.
- https://karanteeni.net/creasaannot vain osassa säännöissä on piste perässä.
- https://karanteeni.net/rankit sivulla eri rankkien eri komennot eivät mene uusille riveille pienellä näytöllä vaan elementti jossa eri ominaisuudet ovat näkyy rumasti.

En ymmärtänyt Naxun muistilistasta mitään joten osa asioista saattaa olla samoja. En tiedä edes että onko yhdenkään näistä virheistä ilmoittamisesta hyötyä mutta tässä on jokunen vika ja pisteen unohtumisia.

**Comment by Ixynas** [comment]
Suurin osa fixattu commitissa https://github.com/Ixynas/karanteeni.github.io/commit/76a5a228b5946331b9466e6c9da1fe905c807b2f
